name: campus_thrift
description: A simple marketplace app for students to buy/sell items on campus.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
   sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.3.3
  loading_animation_widget: ^1.2.0+4
  image_picker: ^1.0.4
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  shared_preferences: ^2.5.4
  fl_chart: ^0.69.0 
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/


